export type RootStackParamsList = {
  TermsUse: undefined;
  Profile: undefined;
  MyPassword: undefined;
  AppTabNav: undefined;
  Register: undefined;
  Login: undefined;
  EditProfile: undefined;
  config: undefined;
  DrawerRoutes: undefined;
  SettingsScreen: undefined;
  EditReg: undefined;
  ResetPassword: undefined;
  ScreenChat: undefined;
  TrainingPartnerRegister: undefined;
  TrainingPartnerSearch: undefined;
  MacroTracker: undefined;
  UserSearch: {selectedItem: any};
  Chat: {selectedItem: any};
  Followers_Followed: {type: string; id: any};
  Requests: undefined;
  Events: undefined;
  EventsRegister: undefined;
  EventsSearch: undefined;
  EventParticipants: {eventoId: number};
};
